# Stage 1: base environment with CUDA and Miniconda
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

# Avoid interactive frontend
ENV DEBIAN_FRONTEND=noninteractive

# Create non-root user
RUN useradd -m -u 1000 user
WORKDIR /workspace

# Install basic tools and dependencies
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*


# Install Miniconda
ENV CONDA_DIR=/opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    bash ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh
ENV PATH=$CONDA_DIR/bin:$PATH

# Set working directory
#WORKDIR /workspace


CMD ["/bin/bash"]

